name: Deploy Brello to PROD
on:
  push:
    branches:
      - main
      - setup-cicd
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cahce: yarn

      - name: Enable Corepack
        run: corepack enable
        
      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build
        env:
          NODE_ENV: production